project_id = "xsscqmlrnrodwydmgvac"

[functions.create-user]
verify_jwt = true

[functions.init-superadmin]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.send-sms-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.create-reservation-direct]
verify_jwt = false

[functions.send-sms-message]
verify_jwt = false

[functions.generate-offer-pdf]
verify_jwt = false


[functions.manage-instance-users]
verify_jwt = false

[functions.reset-password]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.get-manifest]
verify_jwt = false


[functions.send-offer-email]
verify_jwt = false

[functions.get-customer-info]
verify_jwt = false

[functions.test-sentry-error]
verify_jwt = false

[functions.send-offer-reminders]
verify_jwt = false

[functions.get-embed-config]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-protocol-email]
verify_jwt = false

[functions.create-apaczka-shipment]
verify_jwt = false
