export const VAT_RATE = 0.23;
export const CUSTOMER_SEARCH_MIN_LENGTH = 2;

export const formatCurrency = (value: number) =>
  value.toLocaleString('pl-PL', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + ' zł';

export const COUNTRIES = [
  { code: 'PL', name: 'Polska' },
  { code: 'DE', name: 'Niemcy' },
  { code: 'CZ', name: 'Czechy' },
  { code: 'SK', name: 'Słowacja' },
  { code: 'UA', name: 'Ukraina' },
  { code: 'LT', name: 'Litwa' },
  { code: 'FR', name: 'Francja' },
  { code: 'GB', name: 'Wielka Brytania' },
  { code: 'IT', name: 'Włochy' },
  { code: 'ES', name: 'Hiszpania' },
  { code: 'NL', name: 'Holandia' },
  { code: 'BE', name: 'Belgia' },
  { code: 'AT', name: 'Austria' },
  { code: 'CH', name: 'Szwajcaria' },
  { code: 'SE', name: 'Szwecja' },
  { code: 'NO', name: 'Norwegia' },
  { code: 'DK', name: 'Dania' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'PT', name: 'Portugalia' },
  { code: 'IE', name: 'Irlandia' },
  { code: 'HU', name: 'Węgry' },
  { code: 'RO', name: 'Rumunia' },
  { code: 'BG', name: 'Bułgaria' },
  { code: 'HR', name: 'Chorwacja' },
  { code: 'SI', name: 'Słowenia' },
  { code: 'EE', name: 'Estonia' },
  { code: 'LV', name: 'Łotwa' },
  { code: 'GR', name: 'Grecja' },
  { code: 'US', name: 'Stany Zjednoczone' },
  { code: 'CA', name: 'Kanada' },
  { code: 'CN', name: 'Chiny' },
  { code: 'JP', name: 'Japonia' },
  { code: 'KR', name: 'Korea Południowa' },
  { code: 'AU', name: 'Australia' },
  { code: 'BY', name: 'Białoruś' },
  { code: 'TR', name: 'Turcja' },
  { code: 'RU', name: 'Rosja' },
] as const;
